const pointGuards = [
    { name: `Stephen Curry`, position: `PG`, rpm: 7.72 },
    { name: `Damian Lillard`, position: `PG`, rpm: 5.56 },
    { name: `Mike Conley`, position: `PG`, rpm: 5.5 },
    { name: `Kyle Lowry`, position: `PG`, rpm: 4.9 },
    { name: `Jrue Holiday`, position: `PG`, rpm: 4.44 },
    { name: `Devonte' Graham`, position: `PG`, rpm: 4.09 },
    { name: `Lonzo Ball`, position: `PG`, rpm: 3.99 },
    { name: `Kyrie Irving`, position: `PG`, rpm: 3.82 },
    { name: `Patty Mills`, position: `PG`, rpm: 3.43 },
    { name: `Chris Paul`, position: `PG`, rpm: 3.1 },
    { name: `Jamal Murray`, position: `PG`, rpm: 3.07 },
    { name: `Patrick Beverley`, position: `PG`, rpm: 2.95 },
    { name: `Cameron Payne`, position: `PG`, rpm: 2.9 },
    { name: `Ben Simmons`, position: `PG`, rpm: 2.76 },
    { name: `De'Aaron Fox`, position: `PG`, rpm: 2.72 },
    { name: `LaMelo Ball`, position: `PG`, rpm: 2.64 },
    { name: `Jordan Clarkson`, position: `PG`, rpm: 2.63 },
    { name: `Luka Doncic`, position: `PG`, rpm: 2.03 },
    { name: `Goran Dragic`, position: `PG`, rpm: 1.97 },
    { name: `Marcus Smart`, position: `PG`, rpm: 1.88 },
    { name: `Trae Young`, position: `PG`, rpm: 1.79 },
    { name: `Monte Morris`, position: `PG`, rpm: 1.79 },
    { name: `Derrick White`, position: `PG`, rpm: 1.61 },
    { name: `Dejounte Murray`, position: `PG`, rpm: 1.05 },
    { name: `Dennis Schroder`, position: `PG`, rpm: 1.03 },
    { name: `Ish Smith`, position: `PG`, rpm: 0.97 },
    { name: `George Hill`, position: `PG`, rpm: 0.8 },
    { name: `Malcolm Brogdon`, position: `PG`, rpm: 0.58 },
    { name: `Avery Bradley`, position: `PG`, rpm: 0.32 },
    { name: `Trey Burke`, position: `PG`, rpm: 0.22 },
    { name: `D'Angelo Russell`, position: `PG`, rpm: 0.19 },
    { name: `Carsen Edwards`, position: `PG`, rpm: 0.17 },
    { name: `Ryan Arcidiacono`, position: `PG`, rpm: 0.03 },
    { name: `Ja Morant`, position: `PG`, rpm: -0.05 },
    { name: `Chris Chiozza`, position: `PG`, rpm: -0.08 },
    { name: `Kemba Walker`, position: `PG`, rpm: -0.13 },
    { name: `Tyler Herro`, position: `PG`, rpm: -0.26 },
    { name: `John Wall`, position: `PG`, rpm: -0.29 },
    { name: `Jalen Brunson`, position: `PG`, rpm: -0.4 },
    { name: `Collin Sexton`, position: `PG`, rpm: -0.46 },
    { name: `Reggie Jackson`, position: `PG`, rpm: -0.49 },
    { name: `Tyrese Haliburton`, position: `PG`, rpm: -0.58 },
    { name: `Jevon Carter`, position: `PG`, rpm: -0.73 },
    { name: `Payton Pritchard`, position: `PG`, rpm: -0.77 },
    { name: `Raul Neto`, position: `PG`, rpm: -0.86 },
    { name: `Brandon Goodwin`, position: `PG`, rpm: -0.91 },
    { name: `Tyus Jones`, position: `PG`, rpm: -0.95 },
    { name: `Russell Westbrook`, position: `PG`, rpm: -1.04 },
    { name: `Edmond Sumner`, position: `PG`, rpm: -1.05 },
    { name: `Ricky Rubio`, position: `PG`, rpm: -1.08 },
    { name: `Facundo Campazzo`, position: `PG`, rpm: -1.3 },
    { name: `T.J. McConnell`, position: `PG`, rpm: -1.34 },
    { name: `Coby White`, position: `PG`, rpm: -1.44 },
    { name: `D.J. Augustin`, position: `PG`, rpm: -1.51 },
    { name: `Jordan McLaughlin`, position: `PG`, rpm: -1.61 },
    { name: `Austin Rivers`, position: `PG`, rpm: -1.87 },
    { name: `Brad Wanamaker`, position: `PG`, rpm: -2.05 },
    { name: `Derrick Rose`, position: `PG`, rpm: -2.17 },
    { name: `Malachi Flynn`, position: `PG`, rpm: -2.19 },
    { name: `Aaron Holiday`, position: `PG`, rpm: -2.21 }
]
const shootingGuards = []
const smallForwards = []
const powerForwards = []
const centers = []
const reserves = []
